name: Run test suit for engine.
run-name: ${{ github.actor }} running bin/rails test
on: [workflow_dispatch]
jobs:
  Test-Marem-Core:
    runs-on: ubuntu-latest
    environment: testing
    steps:
        - uses: actions/checkout@v4
        - uses: ruby/setup-ruby@v1
          with:
            ruby-version: '3.3' # Not needed with a .ruby-version file
            bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        - run: bundle install
        - run: bundle exec bin/rails test
    